### ISSUE TITLE
Can't work with bootstrap-vue modal

### ISSUE THREAD

**Issue by wwwjun** [weifeiyue/vue-datepicker-local#25]
![image](https://user-images.githubusercontent.com/11974533/35219620-6093759a-ffae-11e7-9972-6d1831e99115.png)
![image](https://user-images.githubusercontent.com/11974533/35219632-6d5bd312-ffae-11e7-92da-0053648d2232.png)

In bootstrap-vue modal, when I click the input, can't show the datepicker-popup

**Comment by developius** [comment]
I'll second this. When clicking on a datepicker inside a modal, the calendar doesn't appear. Directly mutating the `show` data property in the vue devtools causes it to show correctly:

![screenshot 2018-02-20 14 48 21](https://user-images.githubusercontent.com/5836587/36404062-8aaff6cc-164d-11e8-9e48-56dc531dec11.png)


There's something weird going on with the vue events - this screenshot is from clicking on a datepicker inside a modal.

![screenshot 2018-02-20 14 43 33](https://user-images.githubusercontent.com/5836587/36403897-8dea1b7a-164c-11e8-8cd3-3c27fb0cd173.png)

It should be noted that a datepicker _outside_ a modal does _not show any events_ in the vue debugger, but works just fine all the same. I'm guessing it's because it binds directly to `document` [here](https://github.com/weifeiyue/vue-datepicker-local/blob/master/src/VueDatepickerLocal.vue#L168)?

**Comment by weifeiyue** [comment]
@wwwjun @developius [bug fixed @v1.0.11](https://github.com/weifeiyue/vue-datepicker-local/commit/3476b408c47e365e2a6eb2c3848b8f84e84140d7)

**Comment by developius** [comment]
@weifeiyue awesome, thanks! 💯
