### ISSUE TITLE
Dropdown picker location

### ISSUE THREAD

**Issue by paolog22** [weifeiyue/vue-datepicker-local#42]
Hi. how can i set the location of dropdown like left or right ? 
thanks

**Comment by yusren** [comment]
I faced the same problem. Calendars cross the right border of the screen when displayed in mobile browsers. I am forced to customize the **VueDatepickerLocal.vue** in node_module folder (due to my limited knowledge).
Check this code :
[https://pastebin.com/rU9A6Px3]()
In my page Template :
`<vue-datepicker-local :orient=true ... />`

**Comment by paolog22** [comment]
thanks @yusren 
i will check that thanks again.
